version: '3.9'

services:
    test_db:
        image: postgres:14
        container_name: test_db
        ports:
            - '5400:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: tests

    dev_db:
        image: postgres:14
        container_name: dev_db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: haoxigua
        volumes:
            - /Users/qinyu/db/postgres/pgData:/var/lib/postgresql/data
